### ISSUE TITLE
no CAS(ME)2 

### ISSUE THREAD

**Issue by Zhiwu6** [genbing99/SoftNet-SpotME#10]
sorry,but this CAS(ME)2 - http://fu.psych.ac.cn/CASME/cas(me)2-en.php is empety,how can i get the datasets?

**Comment by genbing99** [comment]
Here is the updated link: http://casme.psych.ac.cn/casme/e3

**Comment by Zhiwu6** [comment]
> Here is the updated link: http://casme.psych.ac.cn/casme/e3

Thank you!

**Comment by Zhiwu6** [comment]
&nbsp; 您好，师兄。很抱歉再次打扰你，但是我在复现Softnet论文时，code_final.xlsx文件显示为空，我试着一步一步debug，发现这个不能自己生成，希望师兄可以帮我解答一下这个疑问。
&nbsp; 感谢师兄，感谢师兄，感谢师兄！！！



---Original---
From: "Gen ***@***.***&gt;
Date: Fri, May 26, 2023 13:41 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [genbing99/SoftNet-SpotME] no CAS(ME)2  (Issue #10)




 
Here is the updated link: http://casme.psych.ac.cn/casme/e3

**Comment by genbing99** [comment]
Same to #11
