### ISSUE TITLE
no file "code_final.xlsx"

### ISSUE THREAD

**Issue by Zhiwu6** [genbing99/SoftNet-SpotME#11]
xl = pd.ExcelFile(dataset_name + '/code_final.xlsx')  # Specify directory of excel file
xlrd.biffh.XLRDError: File size is 0 bytes
How did this file come about? Following the previous steps will not yield this file

**Comment by genbing99** [comment]
The file "code_final.xlsx" should be provided in the CAS(ME)<sup>2</sup> dataset when you request from the dataset link.

**Comment by Zhiwu6** [comment]
thanks，because the dataset request does not pass
