### ISSUE TITLE
trained weight

### ISSUE THREAD

**Issue by Zhiwu6** [genbing99/SoftNet-SpotME#12]
For training data, where are the trained weights saved? Is SOFTNet_Weights\CASME_sq\micro-expression?  When I use pre-trained weight for prediction, is this weight I trained before?  Thank you very much for helping me answer

**Comment by genbing99** [comment]
The trained weights are not saved by default. To save the weights, you need to add the line 
```model.save_weights(path)``` 
after the line 
```model.fit()```
in training.py
