### ISSUE TITLE
Paper Related

### ISSUE THREAD

**Issue by 33220019** [genbing99/SoftNet-SpotME#2]
Can yo tell me about paper related with this project ? thanks

**Comment by genbing99** [comment]
Hi, the paper is currently under review, it will be uploaded once the review stage is passed.

**Comment by 33220019** [comment]
oke thanks

**Comment by 33220019** [comment]
how do i run the ipynb file? Are there any additional settings? I try it on Google Collab, it can't work yet. how to create a path for the cas (me) dataset that I have stored in gdrive without using the weight provided.

**Comment by genbing99** [comment]
To run the ipynb files, you need to install the packages from requirements.txt and follow the file structure as described in the readme file. 
I suggest you download the dataset to your local computer since the storing of pictures and some computations would be more convenient. You can train and validate the softnet model by following the instructions in ipynb files without using the pre-trained weights.

**Comment by 33220019** [comment]
requirements.txt contains 274 packages? and all that must be installed? I use Google Cobab for simulation and not all packages can be installed because there are some errors, either the type of package or the version. any solutions?

**Comment by genbing99** [comment]
All the packages are included in the requirements.txt are to ensure that there is no clashing of version between packages. However, you can try to run the ipynb files, and install the packages if needed, this can reduce the number of packages to be installed.

**Comment by 33220019** [comment]
I have run the Extraction_Preprocess.ipynb file in google colab, but the iteration doesn't work. I have selected CASME_sq. how to determine the path to the dataset? I have put all the datasets and ipynb files in gdrive. thanks

**Comment by 33220019** [comment]
![gambar](https://user-images.githubusercontent.com/73221371/117616501-69e83080-b195-11eb-9fc2-319ef7a00d45.png)

**Comment by 33220019** [comment]
![gambar](https://user-images.githubusercontent.com/73221371/117616697-a87deb00-b195-11eb-9ba6-3ebc12dafb36.png)
![gambar](https://user-images.githubusercontent.com/73221371/117616740-b6cc0700-b195-11eb-84d6-8ef62dba12eb.png)

**Comment by genbing99** [comment]
You should follow the file structure as written in the README. The 'Extraction_Preprocess.ipynb' and 'CASME_sq' should be located under the same level. Maybe you can change your current directory to the location where 'CASME_sq' is located.

**Comment by 33220019** [comment]
How are u today? sorry I want to ask. I just checked it turned out ipynb file for SoftNet-SpotME deleted ? why? when it's  good code. thanks

**Comment by genbing99** [comment]
Hi, we are doing some modifications to the ipynb files, it will be available once the modifications have done.
You may run the py files as they are equivalent.

**Comment by 33220019** [comment]
Okay. I've run ipynb files before and it runs successfully. I'm exploring how to create a framework to recognize micro-expressions from your ipynb program. currently I'm learning to use a jupyter notebook to create an emotion recognition framework from micro-expression using other methods. awaited modification of his ipynb. thanks

**Comment by 33220019** [comment]
I want to ask why the F1 score is small? Under 20% ()2) ?

**Comment by 33220019** [comment]
I want to ask why the F1 score is small? Under 20% (0.2) ?

**Comment by genbing99** [comment]
Please refer to the paper for the explanation. Thank you.
