### ISSUE TITLE
The model may underestimate the number of false positives

### ISSUE THREAD

**Issue by youcaiSUN** [genbing99/SoftNet-SpotME#3]
Hi, thanks for your sharing. 

I ran the code on CASME for micro-expression detection, and I almost reproduced the results reported in the paper (0.1212 vs. 0.1379). However, I found that the evaluation was done only on videos in which micro-expressions occured  (33 vs. 97 (total number), only cover 14 subjects vs. 22 subjects (total number)). Since the model may misjudge non-expression snippets as micro-expression in the rest videos, the number of false positives may be underestimated and the results reported in the paper may be overestimated,

**Comment by genbing99** [comment]
Hi, thank you for your interest in the paper.

We follow the evaluation method in a similar fashion to MEGC 2020. Therefore, the results produced are accurate while we are comparing our results to MEGC 2020.

**Comment by youcaiSUN** [comment]
I got it. Thanks very much!
