### ISSUE TITLE
How create own SoftNet Weight ?

### ISSUE THREAD

**Issue by 33220019** [genbing99/SoftNet-SpotME#4]
May i know how to create own SoftNet Weight in hdf5 file ? can you explain to me or maybe you have a simple code for create it ? thanks

**Comment by genbing99** [comment]
Hi, you can use model.save_weights('path_to_location.hdf5') as documented in Tensorflow Keras platform (https://www.tensorflow.org/guide/keras/save_and_serialize).

**Comment by bleakie** [comment]
请问您知道megc每年什么时候开始举办吗？

**Comment by Androsimus** [comment]
@bleakie as far as I understand, organizers choose appropriate dates every year. As for this year's challenge you can find info on official site https://megc2022.github.io/challenge.html.
