### ISSUE TITLE
How to choose the best model parameters?

### ISSUE THREAD

**Issue by ADstudyer** [genbing99/SoftNet-SpotME#5]
May I know how to choose the best model parameters? or you just save the model after training 10 epochs?

**Comment by genbing99** [comment]
The model parameters are saved after training 10 epochs.

**Comment by ADstudyer** [comment]
Hello, I have the following questions:
1. Why move the ground truth forward by K frames in the spotting process?
In training.py line159:
for samples in video:
            gt.append([samples[0]-k, 0, samples[1]-k, 0, 0, 0, 0])
            total_gt += 1

2. When applying for the SAMM long videos dataset, my application email was regarded as spam by the server and could not be sent to the mailbox of the person in charge. I'm curious how did you apply?

**Comment by genbing99** [comment]
1. The adjustment is due to the score aggregation mentioned in the paper Section 2.4 where we shifted the spotted intervals forward by k frames, therefore the ground-truth labels are required to be shifted.
2. I am not sure about this, you may email the authors for more details.
