### ISSUE TITLE
How to plot the intervals as in the paper?

### ISSUE THREAD

**Issue by xjtupanda** [genbing99/SoftNet-SpotME#6]
Thanks a lot for your work and code! I've learned a lot from that, including how to plot the peak graph. But there is no corresponding code for plotting the intervals, including Ground-truth and predictions. Did you plot those also using matplotlib? Could you please tell me how to plot those?

**Comment by genbing99** [comment]
Hi, you can change the parameter to visualize the plot that contains ground-truth and threshold lines. 
``` python main.py --show_plot True```
The prediction lines are not included in the plot due to the overcomplicated plot which reduces the readability.
