### ISSUE TITLE
Training data set

### ISSUE THREAD

**Issue by YUZHIWANG-bug** [genbing99/SoftNet-SpotME#7]
Can I only use cas (me) ^ 2 for training? If so, can you provide a pre-trained model？Thank you very much!

**Comment by genbing99** [comment]
Hi, the pre-trained models have been provided in the folder SOFTNet_Weights.
If you wish to continue the training, you can replace line 222 in training.py:
```model.set_weights(weight_reset) #Reset weights to ensure the model does not have info about current subject```
with:
```model.load_weights(path)```
Then, run the program by setting the parameters:
``` python main.py --dataset_name CASME_sq --train True```

**Comment by YUZHIWANG-bug** [comment]
> Hi, the pre-trained models have been provided in the folder SOFTNet_Weights. If you wish to continue the training, you can replace line 222 in training.py: `model.set_weights(weight_reset) #Reset weights to ensure the model does not have info about current subject` with: `model.load_weights(path)` Then, run the program by setting the parameters: ` python main.py --dataset_name CASME_sq --train True`

Thank you very much for your reply. I will try to use it. Thank you very much!
