### ISSUE TITLE
Program running problem

### ISSUE THREAD

**Issue by shentianshu** [genbing99/SoftNet-SpotME#8]
I have the SAMM dataset but when I keep having an error that len(samples) is zero in the program of running, is it because I only have  one dataset? I also wonder can this program run on linux? Thank you very much!

**Comment by genbing99** [comment]
You need the SAMM Long Videos dataset instead of the SAMM dataset. I have not tested it on Linux, but I think it should work fine as well.

**Comment by xjtupanda** [comment]
The program can be run on Linux platform.
