### ISSUE TITLE
Questions about paper

### ISSUE THREAD

**Issue by xjtupanda** [genbing99/SoftNet-SpotME#9]
Hello! I'm trying to make a picture like Fig.1 in the paper, i.e.,  teaser.png in SoftNet-SpotME/images. Specifically, how did you make the heat-map/attention-map type pictures in the middle column and on the right? I guess the reddish parts mean higher intensity and the bluish parts indicate weaker. Is it made by placing an intensity mask onto the original picture? I would appreciate it very much if you could share the code. Thanks in advance!

**Comment by genbing99** [comment]
Hi, sorry for the late reply. I do not keep the old codes with me, as it was 2 years back.

We use the gradcam to compute the class activation map, then it is placed on the original picture to visualize the activated regions.

**Comment by xjtupanda** [comment]
> Hi, sorry for the late reply. I do not keep the old codes with me, as it was 2 years back.
> 
> We use the gradcam to compute the class activation map, then it is placed on the original picture to visualize the activated regions.

Thank you so much! Problem solved.
